### PR TITLE
Adopt ember-ignore-children-helper

### PR DESCRIPTION
**Pull request by bjornharrtell**
Intends to resolve https://github.com/yapplabs/ember-modal-dialog/issues/337.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@lukemelia friendly nudge to ask if this is acceptable.

**Comment by lukemelia** [comment]
@bjornharrtell This looks fine except we should not have a license file in addon/helpers.

**Comment by bjornharrtell** [comment]
@lukemelia are you sure? it's the license from the adopted code, it says it has to be redistributed with the code.

**Comment by bjornharrtell** [comment]
Of course, perhaps it's better to inline that in the code itself?

**Comment by lukemelia** [comment]
> Of course, perhaps it's better to inline that in the code itself?

Yes, inline in the helper file would be appropriate.

**Comment by bjornharrtell** [comment]
@lukemelia done

**Comment by lukemelia** [comment]
Thanks @bjornharrtell!

**Pull request merged**
