### PR TITLE
Fixes #275

### LINKED ISSUE #275: Deprecation Warnings On 3.8+
Started upgrading projects to the latest LTS this morning, and ran into the following deprecation warning for projects using ember-modal-dialog.

https://deprecations.emberjs.com/v3.x/#toc_computed-property-override

https://github.com/yapplabs/ember-modal-dialog/blob/399dc67c8a220505f0631845872280f24b88e32d/addon/components/modal-dialog.js#L17 appears to be the issue.

### PR DESCRIPTION
**Pull request by benkiefer**
This brings you pretty-much current, and ember try:each is passing. It also fixes all the deprecation warnings I was seeing.

Let me know if I can help in any other way.

### CODE REVIEW

**Comment by benkiefer** [comment]
There are still additional deprecations during the build coming from things like ember-tether, but this is still a step forward.

**Comment by jrjohnson** [comment]
@benkiefer could you split this up? I think the deprecation cleanup deserves it's own PR and then the dependency stuff can get handled as well. Needs a rebase at least if you're able to.

**Comment by psbanka** [comment]
Would love to see this merged soon, as I imagine a lot of people are as we get closer to 4.0 being released.

**Comment by lukemelia** [comment]
I rebased this and dropped the ember upgrade portion of it. Thanks @benkiefer. Sorry for the long delay!

**Pull request merged**
