### PR TITLE
Swap the modal-dialog template based on Ember version.

### LINKED ISSUE #34: Template Deprecations (due to `bind-attr` and `classNameBindings`) with 1.13+.
The [addon/templates/components/modal-dialog.hbs](https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/templates/components/modal-dialog.hbs#L3) is triggering the following deprecations on Canary builds:

```
DEPRECATION: The `bind-attr` helper ('modules/ember-modal-dialog/templates/components/modal-dialog.hbs' @ L3:C11) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/Users/rwjblue/src/work/cardstack/takeoff/bower_components/ember/ember-template-compiler.js:9692:24)
        at /Users/rwjblue/src/work/cardstack/takeoff/bower_components/ember/ember-template-compiler.js:9568:15
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15489:7)
        at visitors.Program (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15499:16)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15490:12)
        at visitors.BlockStatement (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15510:14)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15490:12)
DEPRECATION: You're using legacy class binding syntax: classBinding="containerClassNamesString alignmentClass renderInPlaceClass container-class" @ 5:45 in (inline). Please replace with class=""
        at /Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:10241:26
        at each (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:10308:7)
        at /Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:10226:7
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15489:7)
        at visitors.Program (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15499:16)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
        at Walker.visit (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15490:12)
        at visitors.BlockStatement (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15510:14)
        at Walker.children (/Users/rwjblue/src/work/foo-bar/bower_components/ember/ember-template-compiler.js:15522:7)
```

### PR DESCRIPTION
**Pull request by rwjblue**
Updates to use library that @lukemelia and I worked on at WGE to detect the Ember version, and use a different template as needed.

Requires a release of ember-tether including https://github.com/yapplabs/ember-tether/pull/4 before the internal ember-tether + ember-modal-dialog tests will pass in 1.13.

Closes #41.
Fixes #34.

### CODE REVIEW

**Comment by chrislopresto** [comment]
Looks good to me. Thoughts, @lukemelia?

**Comment by lukemelia** [comment]
:+1: Thanks, @rwjblue!

**Comment by ef4** [comment]
I tried this out with 2.0 beta and it doesn't work because 

    require('semver').satisfies('2.0.0-beta.1', '>= 1.13.0') === false

**Comment by sandstrom** [comment]
Thanks @rwjblue!

**Comment by rwjblue** [comment]
@ef4 - Thanks for reporting! https://github.com/yapplabs/ember-modal-dialog/pull/44 should fix...

**Pull request merged**
