### PR TITLE
Fix error attempting to join class names when they are a string

### PR DESCRIPTION
**Pull request by lukemelia**
- previously these properties were concatenated properties so they were guaranteed to be an array. now they may be strings or arrays

### CODE REVIEW

**Comment by tszymon** [comment]
Hi @lukemelia 👋  Would it be possible to release a new add-on version which includes this fix? Thank you in advance.

**Comment by danr1979** [comment]
> Hi @lukemelia wave Would it be possible to release a new add-on version which includes this fix? Thank you in advance.

That would be great for us too.

**Comment by dpigera** [comment]
> 

Running into the same issue while upgrading to ember 3.28.5. Would really appreciate it too @lukemelia :)

**Comment by lukemelia** [comment]
Released as 4.0.1 @dpigera @danr1979 @tszymon

**Comment by danr1979** [comment]
Thank you very much.  Working fine now.

**Comment by tszymon** [comment]
Thank you! Much appreciated.

**Pull request merged**
