### PR TITLE
Removing jQuery

### LINKED ISSUE #227: Running without jquery
Are you interested in tracking this effort? I tried to go without jQuery in our app (we aren't using it directly), but the remaining console error was from here.

### PR DESCRIPTION
**Pull request by gmurphey**
Closes #227.

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
This has been ready for 2 months - can we get it merged? Completely broken in Ember 2.18 and this should fix it

**Comment by BryanCrotaz** [comment]
@lukemelia  nudge

**Comment by lukemelia** [comment]
Thanks for this PR @gmurphey and for the nudge @BryanCrotaz. There are a lot of changes here. I would feel more comfortable merging if a few people could try out this PR in their app and give it a thumbs up.

**Comment by BryanCrotaz** [comment]
How do you reference a PR in npm?

**Comment by gmurphey** [comment]
@BryanCrotaz should be able to use `gmurphey/ember-modal-dialog#no-jquery` in place of the version.

**Comment by BryanCrotaz** [comment]
I started by searching for it to fork it, but github sayeth **We couldn’t find any repositories matching 'gmurphey/ember-modal-dialog'**

**Comment by gmurphey** [comment]
@BryanCrotaz here's the fork: https://github.com/gmurphey/ember-modal-dialog/tree/no-jquery

**Comment by BryanCrotaz** [comment]
Thanks. That's really odd - you're not listed when you search github for ember-modal-dialog, but that link works!

**Comment by BryanCrotaz** [comment]
Tested and worked first time. Without this fix you get an error that document is undefined when closing the dialog.

**Pull request merged**
