### PR TITLE
Fix bug in specifying incorrect overlay selector on iOS.

### PR DESCRIPTION
**Pull request by andrewhavens**

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks. Can you describe what makes this necessary @andrewhavens?

**Comment by andrewhavens** [comment]
I'm not sure if the selector changed at some point, but the current selector is not correct. This has been resulting in the following error:
> null is not an object (evaluating 'document.querySelector("div[data-ember-modal-dialog-overlay]").style')
Since the selector is incorrect, the result of calling `querySelector` returns null, so it fails to set the cursor style on null.

**Comment by scottkidder** [comment]
Indeed, I hit an issue with this and was getting a very cryptic glimmer error until upgrading to ember-cli 3.1.0-beta.1 and ember-source 3.1.0-beta.3 and now the error I am seeing is:
```
basic-dialog.js:52 Uncaught TypeError: Cannot read property 'style' of null
    at Class.makeOverlayClickableOnIOS (basic-dialog.js:52)
    at sendEvent (ember-metal.js:246)
    at Class.trigger [as _super] (evented.js:76)
    at Class.trigger (core_view.js:59)
    at Class.superWrapper [as trigger] (ember-utils.js:428)
    at CurlyComponentManager.didCreate (ember-glimmer.js:4267)
    at Transaction.commit (runtime.js:3024)
    at Environment$1.commit (runtime.js:3110)
    at Environment$1.commit (ember-glimmer.js:3464)
    at InteractiveRenderer._renderRoots (ember-glimmer.js:4816)
(anonymous) @ basic-dialog.js:52
sendEvent @ ember-metal.js:246
trigger @ evented.js:76
trigger @ core_view.js:59
superWrapper @ ember-utils.js:428
didCreate @ ember-glimmer.js:4267
commit @ runtime.js:3024
commit @ runtime.js:3110
commit @ ember-glimmer.js:3464
_renderRoots @ ember-glimmer.js:4816
_renderRootsTransaction @ ember-glimmer.js:4841
_revalidate @ ember-glimmer.js:4881
invoke @ backburner.js:247
flush @ backburner.js:167
flush @ backburner.js:325
_end @ backburner.js:772
end @ backburner.js:514
_run @ backburner.js:817
_join @ backburner.js:793
join @ backburner.js:568
run.join @ ember-metal.js:456
handler @ ember-glimmer.js:5908
(anonymous) @ event_dispatcher.js:234
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
```

**Comment by lukemelia** [comment]
Closed in favor of #245

**Pull request closed without merging**
