### PR TITLE
avoid sass dependency

### PR DESCRIPTION
**Pull request by artych**
Motivation: to keep addon minimal (and therefore more awesome), since:
- `sass` is not necessary for 30 `css` lines maintaining,
- consuming app could be `less` (or even `css`) styled.

### CODE REVIEW

**Comment by raycohen** [comment]
I'm in favor of removing the sass dependency here.

**Comment by Scott3377** [comment]
bump

**Comment by chrislopresto** [comment]
We do specify `ember-cli-sass` as a devDependency rather than a dependency. But removing it in favor of css examples probably makes sense regardless. The packaged scss partials will almost always need to be supplemented.

Thoughts, @lukemelia?

Also, we'd need a rebase.

**Comment by artych** [comment]
> We do specify ember-cli-sass as a devDependency rather than a dependency

"Including In An Ember Application" section of the Readme looks like `ember-cli-sass` is required for consuming app.

**Comment by lukemelia** [comment]
I'm +1 on making sass seem as optional as it is and providing a vanilla css path.

**Comment by artych** [comment]
@chrislopresto, it's rebased, sir!

**Comment by qnsi** [comment]
Any news? I would also prefer not to include sass.

**Comment by chrislopresto** [comment]
@artych @qnsi Sorry for the delay... just had some time to think this through a bit.

We're on board for removing the sass dependency, but we'd like to keep the scss partial files so those using sass could retain the current flexibility. I'm working on a less project right now, so I'm about to need some less partials as well.

If you have some time to rejigger, go for it. Otherwise I hope to get to this within the next week.. or two.. or :hourglass:

**Comment by jherdman** [comment]
Hey gang. I was just looking at this very problem as we're migrating an app to PostCSS. Is there anything I can do to help this along?

**Comment by jevanlingen** [comment]
For those whom already want to avoid using sass, just don't install the sass dependency (i.e. just only run `ember install ember-modal-dialog`). After installing, just copy the css in your project!

**Pull request closed without merging**
