### PR TITLE
Yield 'this' to have access to the component for block params

### LINKED ISSUE #151: Yield `this` in the templates to enable block params
[Block Params](https://guides.emberjs.com/v2.8.0/components/block-params/) can be used to add an exit animation.

### PR DESCRIPTION
**Pull request by RustyToms**
closes #151 

This can be used to enable animations, particularly exit animations. If I get the chance I'll try to make some PRs later to add animation timing and callback options. But for now this will allow users to extend the modal-dialog and tether-dialog components to implement custom animations or other methods where they need to share data from the block component to the template.

https://guides.emberjs.com/v2.8.0/components/block-params/

### CODE REVIEW

**Comment by RustyToms** [comment]
The accepted answer to [this stackoverflow question](http://stackoverflow.com/questions/28506369/how-to-fire-components-actions-from-template-inserted-in-block-form-component-e) gives a good example of how this code can be used.

**Comment by lukemelia** [comment]
Hi @RustyToms, I'm open to something like this, but I would prefer to yield an object that exposes a well-considered public API rather than the entire component.

**Comment by RustyToms** [comment]
This is useful because I can easily extend the component to add some custom functionality, but I cannot extend the template. I must completely overwrite it, but I consider the templates "private API" and subject to change, so it is dangerous to do so. On the other hand, I would not expect this library to yield custom objects based on individual users needs. Yielding `this` allows me and everyone else to create an extension of the addon component with whatever actions I would like.

Perhaps there is an alternative I am failing to consider?

**Comment by lukemelia** [comment]
@RustyToms an example of the approach I would prefer is what `ember-basic-dropdown` does here: https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/templates/components/basic-dropdown.hbs

**Pull request closed without merging**
