### PR TITLE
Add aria attributes to basic dialogs

### PR DESCRIPTION
**Pull request by eshtadc**
Picking up the work from https://github.com/yapplabs/ember-modal-dialog/pull/116 to begin to address https://github.com/yapplabs/ember-modal-dialog/issues/47

Todo:
- [ ] Determine how to handle tether modals
- [ ] Focus management

### CODE REVIEW

**Comment by eshtadc** [comment]
As I mentioned in the other PR comments - aria attributes aren't automatically passed through to ember-tether, so we don't really have a good way to attach the `aria-labelledby` and `aria-describe-by` - only the `role`. There were some attempts to handle this https://github.com/emberjs/ember.js/issues/13224 and it is discussed in the RFC here: https://github.com/emberjs/rfcs/pull/242. This looks promising: https://github.com/mmun/ember-component-attributes/issues/2

**Comment by lukemelia** [comment]
Thanks for your work on this so far @eshtadc! It does seem important for developer ergonomics of this library that we have a consistent treatment of these attributes across the usage patterns. I'll keep this PR open until we can come up with a solution.

**Comment by eshtadc** [comment]
@lukemelia How do you feel about introducing the use of [ember-component-attributes](https://github.com/mmun/ember-component-attributes)? It allows the passing of HTML attributes to any component (including the `ember-tether` components used for tethered display). I played with it locally with some success. Another option I can think of would be to open a PR against [ember-tether](https://github.com/yapplabs/ember-tether) to allow aria attributes either explicitly or through the use of `ember-component-attributes`. It mentions only being tested as far as Ember 2.8 (since it uses a transform) so that may be a concern.

**Comment by lukemelia** [comment]
@eshtadc I would prefer to maintain backward compatibility through the full 2.x series at least until 3.0. I think a PR against ember-tether for explicit support of these aria attributes could work though.

**Comment by eshtadc** [comment]
I'm opening this in ember-tether: https://github.com/yapplabs/ember-tether/issues/50

**Comment by frankeld** [comment]
@eshtadc @lukemelia Any plans to continue work here? I'd be happy to help!

**Comment by eshtadc** [comment]
Closing as out of date.

**Pull request closed without merging**
