### PR TITLE
Add splattibutes support and fix containerClassNames for rendered in place modals

### PR DESCRIPTION
**Pull request by ratierd**
containerClassNames are not passed to the rendered in place modal.
Or rather the property is overriden by the component.

This PR allows us to have rendered in place modals take in the containerClassNames property

### CODE REVIEW

**Comment by ratierd** [comment]
Hello @lukemelia ! Can you approve the workflow/PR ? I followed the contributing doc and script should be good.

Do I need to update the package/changelog in this PR or should I make another PR after this one to release a patch version ?

**Comment by lukemelia** [comment]
Thanks for working on this @ratierd. I'd like to see this PR have a test so that we don't accidentally regress this improvement. As far as package version and changelog, it should not be in this PR. It is handled automatically by our release process.

**Comment by ratierd** [comment]
> Thanks for working on this @ratierd. I'd like to see this PR have a test so that we don't accidentally regress this improvement. As far as package version and changelog, it should not be in this PR. It is handled automatically by our release process.

Thanks for the quick reply !

I added some tests for containerClassNames given a rendered in place modal.

I also added a splattributes for the modals and some tests along with it

**Comment by lukemelia** [comment]
@ratierd this is looking good. please rebase on master to get the commit I just merged, which should resolve the CI failure.

**Comment by ratierd** [comment]
> @ratierd this is looking good. please rebase on master to get the commit I just merged, which should resolve the CI failure.

Done ! Thanks a lot 😄

**Review by lukemelia — APPROVED** [review]

**Comment by lukemelia** [comment]
Released as 4.1.0

**Pull request merged**
