### PR TITLE
Add version check for minimum ember-cli version

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by lukemelia** [comment]
@krisselden any idea about this failure: https://travis-ci.org/yapplabs/ember-modal-dialog/jobs/71027066 ? There is an error logged: `Error: Assertion Failed: BUG: Render node exists without concomitant env.` https://dl.dropboxusercontent.com/s/dlorgoct6ep44t9/2015-07-15%20at%202.12%20AM.png?dl=0

**Comment by krisselden** [comment]
@lukemelia my guess that it is a double destroy bug? the associated node has been destroyed already?

**Comment by chrislopresto** [comment]
@lukemelia Rebase 'o clock. :clock1030:

**Comment by lukemelia** [comment]
Rebased. Have a look and merge at will @chrislopresto

**Pull request merged**
