### PR TITLE
Clean Up Switch Statement

### PR DESCRIPTION
**Pull request by billpull**

### CODE REVIEW

**Comment by lukemelia** [comment]
Nice cleanup. Are you using this in an app?

**Comment by billpull** [comment]
Not currently was taking a peak to see an example of how to structure ember components

**Comment by lukemelia** [comment]
Cool. I'll hold off on merging until I can verify it working in one of our apps, but thanks for the contribution!

**Comment by chrislopresto** [comment]
@billpull We just merged some significant changes into master. But this `switch` statement is actually a bit worse for the wear. Any chance you want to take another pass?

**Comment by lukemelia** [comment]
Closing for now. Feel free to open a new PR if you resurrect this.

**Pull request closed without merging**
